# Generated by Django 5.0.7 on 2024-08-06 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='career',
        ),
        migrations.RemoveField(
            model_name='jobportal',
            name='career',
        ),
        migrations.RemoveField(
            model_name='joblink',
            name='career',
        ),
        migrations.AddField(
            model_name='course',
            name='career_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='joblink',
            name='career_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobportal',
            name='career_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='SelectedCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_name', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('skills_required', models.JSONField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Career',
        ),
    ]
