# Generated by Django 5.0.7 on 2024-08-10 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_remove_course_career_remove_jobportal_career_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobLink',
        ),
        migrations.RenameField(
            model_name='jobportal',
            old_name='career_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='course',
            name='career_name',
        ),
        migrations.RemoveField(
            model_name='jobportal',
            name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='career',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='career.selectedcareer'),
        ),
        migrations.AddField(
            model_name='jobportal',
            name='career',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_portals', to='career.selectedcareer'),
        ),
        migrations.AddField(
            model_name='jobportal',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobportal',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
