# Generated by Django 5.0.7 on 2024-08-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_remove_assessmentquestion_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='selected_option',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
